name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        data:
          - { name: "João Silva", job: "Médico" }
          - { name: "Maria Souza", job: "Advogada" }
          - { name: "Carlos Alberto", job: "Engenheiro" }
          - { name: "Ana Paula", job: "Arquiteta" }
          - { name: "Lucas Lima", job: "Professor" }
          - { name: "Fernanda Costa", job: "Designer" }
          - { name: "Rafael Gomes", job: "Desenvolvedor" }
          - { name: "Juliana Ribeiro", job: "Jornalista" }
          - { name: "Bruno Fernandes", job: "Contador" }
          - { name: "Camila Martins", job: "Enfermeira" }
          

    steps:
      - uses: actions/checkout@v4

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Run API tests (matrix)
        env:
          NAME: ${{ matrix.data.name }}
          JOB: ${{ matrix.data.job }}
        run: |
          echo "Running test for: $NAME - $JOB"
          postman collection run "11108942-8d30e54b-fb26-4749-bacb-61c22d1a2835" \
            -e "11108942-1de5b567-21e5-48bb-81fa-3192ba25873d" \
            --env-var "name=$NAME" \
            --env-var "job=$JOB"
